### ISSUE TITLE
学习搭建博客

### ISSUE THREAD

**Issue by trouvailleme** [metaescape/hugchange.life#1]
你好，你的博客看起来非常舒服，本人不是计算机专业喜欢折腾，可以请教一下博客搭建的大致流程嘛

**Comment by metaescape** [comment]
你好，感谢对这个博客的喜爱。我是 emacs 用户，用 org 格式的文件（和markdown 很相似）写文章， 然后基于emacs 自带的  导出功能转成 html，但这个 html 比较原始，所以自己写了一个程序和 css/js 样式 https://github.com/metaescape/orgchange , 对 html 进行了修饰。
1. 如果你已经了解 emacs或org，可以参考 https://www.hugchange.life/posts/orgchange.html 里前章介绍的使用方式，照着来应该可以导出和我一样的 blog，如果有细节问题可以在这继续讨论。
2. 但如果你没有接触过 emacs 或者 org 文件，那还是需要相当长时间的学习，我不是很推荐直接用我的方式去导出。

  可以考虑基于 markdown 的静态博客生成器，比如 hugo， Pelican 等，这些一般只要你写好了 markdown 文件，然后选择别人开发好的主题就可以导出成 blog 了. 这样的话你不需要了解 emacs或者org。等你学会 hugo 这类工具，想要设计自己的主题样式或者接近我这个 blog 的主题，可以参考以下目录里的 css 样式：https://github.com/metaescape/orgchange/tree/main/themes/darkfloat.  去修改别人主题里的 css 文件, 这需要了解一点Html/css 知识。

导出到本地之后，要能够通过域名访问，还需要远程部署。这也有很多选择，可以自己买各大云厂商的远程服务器（最基础的就可以）,购买域名备案，然后把本地 blog 推送到远程服务器上。也可以基于其他托管平台，比如 github， 相当于 github 给你提供服务器，你只需要把本地 html 推送到 github 的仓库（类似当前这个），然后去 github 开通一个网页托管服务，就能够通过 github.io 的域名去访问。

总之整个过程还是比较多细节的，但核心就是把某个格式的文章转成 html， 然后把 html 文件放在一个公共的别人能访问的服务器上。 最好根据自己当前已经了解的东西，快速把整个流程走一遍，比较快的是 markdown+hugo+github 部署，这个过程里不需要购买服务器申请域名备案等等，也不需要编程（但需要了解hugo等配置方式），找个视频跟下来可能几个小时后就能访问自己页面了(或者搜索其他人用 hugo 搭建的 blog 里介绍的方法，比如：https://cuttontail.blog/blog/create-a-wesite-using-github-pages-and-hugo/).  总体流程稳定后再考虑优化不同的环节、设计自己的主题, 这就要开始学一写编程语言了。

**Comment by trouvailleme** [comment]
> 你好，感谢对这个博客的喜爱。我是 emacs 用户，用 org 格式的文件（和markdown 很相似）写文章， 然后基于emacs 自带的  导出功能转成 html，但这个 html 比较原始，所以自己写了一个程序和 css/js 样式 https://github.com/metaescape/orgchange , 对 html 进行了修饰。
> 
> 1. 如果你已经了解 emacs或org，可以参考 https://www.hugchange.life/posts/orgchange.html 里前章介绍的使用方式，照着来应该可以导出和我一样的 blog，如果有细节问题可以在这继续讨论。
> 
> 2. 但如果你没有接触过 emacs 或者 org 文件，那还是需要相当长时间的学习，我不是很推荐直接用我的方式去导出。
> 
> 
> 
>   可以考虑基于 markdown 的静态博客生成器，比如 hugo， Pelican 等，这些一般只要你写好了 markdown 文件，然后选择别人开发好的主题就可以导出成 blog 了. 这样的话你不需要了解 emacs或者org。等你学会 hugo 这类工具，想要设计自己的主题样式或者接近我这个 blog 的主题，可以参考以下目录里的 css 样式：https://github.com/metaescape/orgchange/tree/main/themes/darkfloat.  去修改别人主题里的 css 文件, 这需要了解一点Html/css 知识。
> 
> 
> 
> 导出到本地之后，要能够通过域名访问，还需要远程部署。这也有很多选择，可以自己买各大云厂商的远程服务器（最基础的就可以）,购买域名备案，然后把本地 blog 推送到远程服务器上。也可以基于其他托管平台，比如 github， 相当于 github 给你提供服务器，你只需要把本地 html 推送到 github 的仓库（类似当前这个），然后去 github 开通一个网页托管服务，就能够通过 github.io 的域名去访问。
> 
> 
> 
> 总之整个过程还是比较多细节的，但核心就是把某个格式的文章转成 html， 然后把 html 文件放在一个公共的别人能访问的服务器上。 最好根据自己当前已经了解的东西，快速把整个流程走一遍，比较快的是 markdown+hugo+github 部署，这个过程里不需要购买服务器申请域名备案等等，也不需要编程（但需要了解hugo等配置方式），找个视频跟下来可能几个小时后就能访问自己页面了(或者搜索其他人用 hugo 搭建的 blog 里介绍的方法，比如：https://cuttontail.blog/blog/create-a-wesite-using-github-pages-and-hugo/).  总体流程稳定后再考虑优化不同的环节、设计自己的主题, 这就要开始学一写编程语言了。

感谢博主的回复，很开心能得到你的分享，之前没有接触过emacs 或者 org 文件，之后想去尝试一下，我是看你发的ubuntu备忘录那篇文章过来的，写的很好，对我很有帮助！最后还是很感谢你的耐心回复，🙏🙏 🙏

**Comment by metaescape** [comment]
那篇也是为了记录自己踩过的坑，很高兴对你有帮助，有别的问题也欢迎讨论

**Comment by trouvailleme** [comment]
好的，感谢🙏
